# Template for Streamlit Cloud secrets
# Replace this with your actual API key in the Streamlit Cloud dashboard
OPENAI_API_KEY = "your-openai-api-key-here"

# Add any other secrets you need for the app here 